### ISSUE TITLE
Unity-Theme database was not found

### ISSUE THREAD

**Issue by LeMutique** [IvanMurzak/Unity-Theme#12]
Just after installing the package this issue appears when clicking on "Window/Unity Theme"

Unity version: 2022.3.5f1
New clean project

**Comment by LeMutique** [comment]
Manually fixed by copying and pasting the database from the release project. Not sure if it's a mistake on my end when installing the package through openupm but working now!

**Comment by IvanMurzak** [comment]
Thanks for the report. It is the same issue with this one: https://github.com/IvanMurzak/Unity-Theme/issues/11
I am working on it already.
