### ISSUE TITLE
Changes in Theme Window not saving

### ISSUE THREAD

**Issue by LeMutique** [IvanMurzak/Unity-Theme#16]
Hey! I opened a ticket recently mentioning that changes made to the theme window didn't save, it happened 3 more times since last time. It seems to be when color changes are made without any changes in the number of themes or colors. When opening back the project, it just loads the old colors that were saved last time. Let me know if you need any kind of detail I can provide! Thank you!

Unity-Theme version: 2.0.1
Unity version: 202.3.5f1

**Comment by IvanMurzak** [comment]
@LeMutique thank you! I reproduced the problem. It was a minor single code line mistake. Already fixed. Please try version `2.0.2`
