### ISSUE TITLE
Error on "Unity-Theme Database" inspector

### ISSUE THREAD

**Issue by antonio-fromsolvers** [IvanMurzak/Unity-Theme#20]
For some reason the Themes on "Unity-Theme Database" is not rendering properly on the inspector.
Any idea why?
<img width="494" alt="Screenshot 2024-06-19 at 13 51 48" src="https://github.com/IvanMurzak/Unity-Theme/assets/130508853/c7516f23-3d17-4a6d-ab29-c7c8764d22a2">

**Comment by antonio-fromsolvers** [comment]
Unity version 2021.3.28.f1

**Comment by IvanMurzak** [comment]
Do you have any compile errors in the project? Possibly the UI was not compiled to be able to render itself.

**Comment by antonio-fromsolvers** [comment]
On unity version 2021.3.28.f1 I wasn't even able to open "Window->Unity-Theme", and was getting a null exception when I tried to open it.
I upgraded unity to version 2022.3.33f1, and now I'm able to open "Window->Unity-Theme", but the "Unity-Theme Database" is still not rendering properly (same as above).

I'm not getting any compile error in the project.

**Comment by antonio-fromsolvers** [comment]
Apart from that, everything seems to be working.
