### ISSUE TITLE
Color still changes while component is disbaled

### ISSUE THREAD

**Issue by iiidefektiii** [IvanMurzak/Unity-Theme#5]
I have to toggle between two color properties. Since I can seem to get it to change colors at runtime with the same component I created two binders one is an active binder and one is a inactive binder for spriterenderers. If I create a prefab and add the components but turn them off they still change the color of the spriterenderer when adding the prefab to my scene even tho they are disabled it still runs on awake.

**Comment by IvanMurzak** [comment]
It sounds like you need to have two different Themes (color palettes), and to switch the Themes in runtime by using this sample
```csharp
Theme.Instance.CurrentThemeName = "Dark";
```
 just use a single ColorBinder per target component.
![Unity-Theme-Palettes](https://github.com/IvanMurzak/Unity-Theme/assets/9135028/1363b9dc-2da8-4be0-8c46-b86b086b77f4)
