### ISSUE TITLE
The type or namespace BaseColorBinder could not be found

### ISSUE THREAD

**Issue by codyrchildress** [IvanMurzak/Unity-Theme#6]
Hi there,

I am unable to extend BaseColorBinder and get a missing assembly reference. I have tried both "using Unity.Theme.Binders" as well as adding my script to the "Unity.Theme.Binders" namespace. 

Am I missing something or is there an issue with this?

Cheers,
Cody

**Comment by IvanMurzak** [comment]
Hi, 
It sounds like you have a script in your Assembly definition. If so, you just need to add `Unity.Theme` as a reference to your Assembly definition.
